<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sender Name Whitelist Request</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #0066cc;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 5px 5px 0 0;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .content {
            background-color: #f8f9fa;
            padding: 30px;
            border-radius: 0 0 5px 5px;
        }
        .highlight-box {
            background-color: #e7f3ff;
            border: 2px solid #0066cc;
            border-radius: 5px;
            padding: 15px;
            margin: 20px 0;
            text-align: center;
        }
        .sender-name {
            font-size: 18px;
            font-weight: bold;
            color: #0066cc;
            letter-spacing: 1px;
        }
        .details-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: white;
        }
        .details-table td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        .details-table td:first-child {
            font-weight: bold;
            background-color: #f8f9fa;
            width: 30%;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">Callbly</div>
        <div>Sender Name Whitelist Request</div>
    </div>
    
    <div class="content">
        <h2>New Sender Name Whitelist Request</h2>
        
        <p>Dear Network Provider,</p>
        
        <p>Please find attached a formal request for sender name whitelist approval. This request has been automatically generated by our system for the following sender name:</p>
        
        <div class="highlight-box">
            <div>Requested Sender Name:</div>
            <div class="sender-name">{{ $sender_name }}</div>
        </div>
        
        <p><strong>Client Details:</strong></p>
        <table class="details-table">
            <tr>
                <td>Client Name:</td>
                <td>{{ $user_name }}</td>
            </tr>
            <tr>
                <td>Email Address:</td>
                <td>{{ $user_email }}</td>
            </tr>
            <tr>
                <td>Company/Organization:</td>
                <td>{{ $company_name }}</td>
            </tr>
            <tr>
                <td>Request Date:</td>
                <td>{{ $request_date }}</td>
            </tr>
        </table>
        
        <p>The attached PDF document contains all the necessary details and formal documentation required for the whitelist approval process. Please review the attached document and process this request according to your standard procedures.</p>
        
        <p>If you require any additional information or have any questions regarding this request, please don't hesitate to contact us.</p>
        
        <p>Thank you for your attention to this matter.</p>
        
        <p>Best regards,<br>
        <strong>Callbly Support Team</strong><br>
        Communications Platform<br>
        Email: support@callbly.com</p>
    </div>
    
    <div class="footer">
        This email was automatically generated by Callbly Communications Platform<br>
        © {{ date('Y') }} Callbly. All rights reserved.
    </div>
</body>
</html>
